package ciudaddeportiva;

/*
 *
 * @author Diego Antonio Lucena Pumar (dlucenap).
 * Copyrigth: (C) 2010 para Diego Antonio Lucena Pumar.
 * License:
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
import java.rmi.*;
import java.util.*;
import javax.swing.*;

public class ModuloControl extends javax.swing.JFrame {

    static iCiudadRMI datosCiudad;

    /** Creates new form Control */
    public ModuloControl() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jLabelTenis = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextTenis = new javax.swing.JTextArea();
        jLabelSaladeMusculacion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextSaladeMusculacion = new javax.swing.JTextArea();
        jButtonActualizar = new javax.swing.JButton();
        jButtonAbrirSaladeMusculacion = new javax.swing.JButton();
        jButtonCerrarSaladeMusculacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelLogo.setFont(new java.awt.Font("Tahoma", 1, 48));
        jLabelLogo.setText("Modulo de Control");

        jLabelTenis.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTenis.setText("Jugadores en Tenis:");

        jTextTenis.setColumns(20);
        jTextTenis.setEditable(false);
        jTextTenis.setRows(5);
        jScrollPane1.setViewportView(jTextTenis);

        jLabelSaladeMusculacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelSaladeMusculacion.setText("Cola Sala de Musculacion:");

        jTextSaladeMusculacion.setColumns(20);
        jTextSaladeMusculacion.setEditable(false);
        jTextSaladeMusculacion.setRows(5);
        jScrollPane2.setViewportView(jTextSaladeMusculacion);

        jButtonActualizar.setText("ACTUALIZAR");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jButtonAbrirSaladeMusculacion.setText("ABRIR SL. MUSCULA.");
        jButtonAbrirSaladeMusculacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirSaladeMusculacionActionPerformed(evt);
            }
        });

        jButtonCerrarSaladeMusculacion.setText("CERRAR SL. MUSCULA.");
        jButtonCerrarSaladeMusculacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSaladeMusculacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTenis)
                            .addComponent(jLabelSaladeMusculacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAbrirSaladeMusculacion, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCerrarSaladeMusculacion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTenis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabelSaladeMusculacion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAbrirSaladeMusculacion, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCerrarSaladeMusculacion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAbrirSaladeMusculacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirSaladeMusculacionActionPerformed
        try {
            datosCiudad.abrirSaladeMusculacion();
        } catch (RemoteException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButtonAbrirSaladeMusculacionActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        //Recibe el estado de la cola de musculacion y de la pista de tenis y muestra todo por pantalla
        try {
            ArrayList<PlantillaDeportista> cola = datosCiudad.estadoColaSaladeMusculacion();
            ArrayList<PlantillaDeportista> local = datosCiudad.estadoPistadeTenis();
            String muestra = "";


            for (int cont = 0; cont
                    < cola.size(); cont++) {
                muestra = muestra + "Identificador: " + String.valueOf(cola.get(cont).getIdentificador());
            }
            jTextSaladeMusculacion.setText(muestra);
            muestra =
                    "";


            for (int cont = 0; cont
                    < local.size(); cont++) {
                muestra = muestra + "Identificador: " + String.valueOf(local.get(cont).getIdentificador());
            }
            jTextTenis.setText(muestra);


        } catch (RemoteException e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonCerrarSaladeMusculacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSaladeMusculacionActionPerformed
        try {
            datosCiudad.cerrarSaladeMusculacion();


        } catch (RemoteException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButtonCerrarSaladeMusculacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                //Recepción del objeto remoto por parte del cliente
                new ModuloControl().setVisible(true);


                try {
                    datosCiudad = (iCiudadRMI) Naming.lookup("//127.0.0.1/ObjetoRMI");


                } catch (NotBoundException e) {
                    System.out.println(e.getMessage());

                } catch (RemoteException e) {
                    System.out.println(e.getMessage());

                } catch (java.net.MalformedURLException e) {
                    System.out.println(e.getMessage());

                }
            }
        });


    }
//192.168.0.128 Puerta de enlace alternativa
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrirSaladeMusculacion;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonCerrarSaladeMusculacion;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelSaladeMusculacion;
    private javax.swing.JLabel jLabelTenis;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    static javax.swing.JTextArea jTextSaladeMusculacion;
    static javax.swing.JTextArea jTextTenis;
    // End of variables declaration//GEN-END:variables
}
